/* NLAg Formulator service worker (generated by src/build.py from src/pwa/sw.template.js — edit the template, not deploy/sw.js).
   Caches the app shell so the app opens with no signal. Only same-origin files are cached: map tiles, OpenStreetMap
   field borders, imagery and elevation always come from the network (Drive mode needs signal to load new borders). */
const VERSION = 'nlag-042bb7d84c8f';
const SHELL = ["./", "index.html", "manifest.webmanifest", "icons/apple-touch-icon.png", "icons/favicon-32.png", "icons/icon-192.png", "icons/icon-512.png", "icons/icon-maskable-512.png"];
self.addEventListener('install', e => {
  // v18: cache: 'reload' so a new version never copies a stale file out of the browser's HTTP cache
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(SHELL.map(u => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});
// v18: when this version replaces an older one, pages still running the OLD page code (v17 and before have no update bar)
// are reloaded once, so they show the new version at once instead of on the next open. Pages from v18 on say hello
// (src/gate.js: { nlagPage }) and are never reloaded by the worker; they show "Update ready — tap to reload" instead.
// Only on an update (an older nlag- cache existed), never on the first install.
const PAGES = 'nlagpages';                                   // not "nlag-…": those are the version caches cleared below
const pageKey = id => new Request(new URL('__nlag_page/' + encodeURIComponent(id), self.registration.scope).href);
const acked = new Set();
self.addEventListener('message', e => {
  const d = e.data, src = e.source; if (!d || !d.nlagPage || !src || !src.id) return;
  acked.add(src.id); e.waitUntil(caches.open(PAGES).then(c => c.put(pageKey(src.id), new Response(String(d.nlagPage)))).catch(() => null));
});
async function reloadOldPages() {
  const wins = await self.clients.matchAll({ type: 'window' }), c = await caches.open(PAGES), keys = await c.keys();
  const live = new Set(wins.map(w => pageKey(w.id).url)), known = new Set();
  await Promise.all(keys.map(r => (live.has(r.url) ? known.add(r.url) : c.delete(r))));   // forget pages that are closed
  const unknown = wins.filter(w => !known.has(pageKey(w.id).url) && !acked.has(w.id)); if (!unknown.length) return;
  unknown.forEach(w => { try { w.postMessage({ nlagPing: VERSION }); } catch (x) { /* gone */ } });   // a v18+ page that loaded a moment ago answers
  await new Promise(r => setTimeout(r, 3000));
  unknown.filter(w => !acked.has(w.id)).forEach(w => { if (w.navigate) w.navigate(w.url).catch(() => null); });
}
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(async keys => {
    const old = keys.filter(k => k.startsWith('nlag-') && k !== VERSION);
    await Promise.all(old.map(k => caches.delete(k)));
    await self.clients.claim();
    if (old.length) reloadOldPages().catch(() => null);      // not awaited: the reload itself needs this worker active
  }));
});
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;            // cross-origin: straight to the network
  if (req.mode !== 'navigate' && (req.cache === 'no-store' || req.cache === 'reload')) return;   // v18: the app's own update check (fetch sw.js no-store) goes to the network; a (hard) reload of the page still falls back to the cached copy offline
  if (req.mode === 'navigate') {                               // the page: network first (get updates), cached copy offline
    // v18: cache: 'no-cache' = always ask the server (a cheap 304 when nothing changed). Before v18 this used the browser's
    // HTTP cache, so for up to the host's max-age (GitHub Pages: 10 min) a normal reload could still get the old page.
    e.respondWith(fetch(req, { cache: 'no-cache' }).then(res => {
      if (res.ok) { const copy = res.clone(); caches.open(VERSION).then(c => c.put('index.html', copy)); }
      return res;
    }).catch(() => caches.match('index.html').then(hit => hit || caches.match('./'))));
    return;
  }
  if (url.pathname.endsWith('/fert-prices.json')) {           // fertilizer prices change a few times a week: network first, cached copy only offline
    e.respondWith(fetch(req, { cache: 'no-store' }).then(res => {
      if (res.ok) { const copy = res.clone(); caches.open(VERSION).then(c => c.put('fert-prices.json', copy)); }
      return res;
    }).catch(() => caches.match('fert-prices.json')));
    return;
  }
  e.respondWith(caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req).then(res => {
    if (res.ok && res.type === 'basic') { const copy = res.clone(); caches.open(VERSION).then(c => c.put(req, copy)); }
    return res;
  })));
});
